### ISSUE TITLE
Redundant ExecutionOperatingUnitType

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/noisepage#1069]
We have redundant `ExecutionOperatingUnitType`s in [brain_defs.h](https://github.com/cmu-db/terrier/blob/master/src/include/brain/brain_defs.h). For example, `HASH_JOIN` is always decomposed into two parts: `HASHJOIN_BUILD` and `HASHJOIN_PROBE`. So the `HASH_JOIN` type is redundant. Similar with the `SORT` type. We need to look into where the redundant types are used and change them to the appropriate types (the ones we have built mini-models for).

**Comment by lmwnshn** [comment]
The redundant types should not be used anywhere. It should be safe to rip out:

Replaced by HASH_AGGREGATE and STATIC_AGGREGATE

- AGGREGATE_BUILD
- AGGREGATE_ITERATE

Replaced by HASH_JOIN

- HASHJOIN_BUILD
- HASHJOIN_PROBE

Replaced by NL_JOIN

- NLJOIN_LEFT
- NLJOIN_RIGHT

Replaced by SORT

- SORT_BUILD
- SORT_ITERATE

**Comment by malin1993ml** [comment]
Thanks, Wan! But I saw some of the redundant types are used in the [compiler_test](https://github.com/cmu-db/terrier/blob/master/test/execution/compiler_test.cpp) though, like the `HASH_JOIN` or the `SORT` type.

**Comment by lmwnshn** [comment]
I think those are in the DISABLED tests right?

**Comment by malin1993ml** [comment]
Not all of them, right? For example, the [SimpleHashJoinTest](https://github.com/cmu-db/terrier/blob/master/test/execution/compiler_test.cpp#L1516) uses `brain::ExecutionOperatingUnitType::HASH_JOIN`.

**Comment by lmwnshn** [comment]
Yes, that is the new one, HASH_JOIN replaced HASHJOIN_BUILD and HASHJOIN_PROBE. Sorry, to clarify above:

Replaced by X (so X is in tpl2 and is being used)

- The old thing which can be removed
- Another old thing which can be removed

**Comment by malin1993ml** [comment]
Thanks for the clarification! But I'm not sure whether that's what we want to do. If `HASHJOIN_BUILD` and `HASHJOIN_PROBE` are executed in two different pipelines, we'll have to measure them separately and have two different operating unit types for them. Unless `HASHJOIN_BUILD` and `HASHJOIN_PROBE` are always executed in a single pipeline in tpl2, which I assume is not the case?

**Comment by lmwnshn** [comment]
Notes from conversation with @malin1993ml (thanks for dropping in!),

- The change in TPL2 is that one OperatorTranslator can now generate multiple pipelines (the ones listed above are examples),
- For now, we can probably get around it by passing in a pipeline pointer to GetFeatureType() so that we can figure out if we're the left or right pipeline (from same OperatorTranslator), i.e. `GetFeatureType(Pipeline *pipeline)` or something similar,
- This will make the new pipeline types unnecessary as it should remain as it was previously.

Alternatively, I refactor the above OperatorTranslators into two OperatorTranslators for the left or right pipeline respectively, which returns us to the original state of affairs. I will try to get a quick estimate of how much work that would be.

**Comment by pmenon** [comment]
Let's discuss this. Splitting the translator into left and right parts should be unnecessary. Moreover, there's some code `OperatorTranslator` that sets child/parent pointers, which doesn't make sense since operators can have multiple children. I'd like to understand how the metrics are being generated and used before proceeding.

**Comment by malin1993ml** [comment]
Well as discussed just now we're going to take the first option (passing in the left/right information while deciding the feature type). Actually this is partially fixed in #1060 (changes to `operating_unit_recorder.cpp`), as now I recall. We still need to get rid of the redundant types though, which should not be difficult.

**Comment by pmenon** [comment]
Makes sense to me 👍

**Comment by lmwnshn** [comment]
We got rid of the redundant types, closing.
