### ISSUE TITLE
Support for VARCHAR, DATE, and TIMESTAMP in selectivity calculation

### ISSUE THREAD

**Issue by arvindsaik** [cmu-db/noisepage#1338]
# Feature Request
## Summary
We need to support `VARCHAR`, `DATE` and `TIMESTAMP` in selectivity calculation. Although the `NewColumnStats` class is templated, storing the underlying value of `DATE`, `TIMESTAMP` and `VARCHAR` in the histogram class causes issues. This is because the current histogram implementation requires that the underlying value for the above mentioned types support operators like '-' (subtract two dates), '*' (multiply a date by a number) and '/' (divide a date by a number). Any solution for a histogram class that supports all types can be easily plugged into the system as long as the APIs remain the same.

## Solution
To support all types:
- Search for an equi-depth histogram implementation that does not require such operators.

To support `DATE` and `TIMESTAMP`:
- The underlying values can be represented as `double` which is a supported type in the histogram implementation. This would require special treatment of `DATE` and `TIMESTAMP` in the templated `NewColumnStats` and `SelectivityUtil` classes.

### Alternatives
In the case that one histogram implementation cannot support all datatypes, have an abstract class for Histogram and have different implementations depending on the datatype of the column.

**Comment by jkosh44** [comment]
DATE and TIMESTAMP are now supported since they use Julian Dates. I don't know exactly which PR made this change though.
https://github.com/cmu-db/noisepage/blob/8896d8ec203ecf8019ecfa0dd5af449d64fdc144/src/include/execution/sql/runtime_types.h#L113-L114
https://github.com/cmu-db/noisepage/blob/8896d8ec203ecf8019ecfa0dd5af449d64fdc144/src/include/execution/sql/runtime_types.h#L302-L303

VARCHAR and VARBINARY still don't work with the Histogram object.

**Comment by jkosh44** [comment]
VARCHAR and VARBINARY support added in this commit specifically, for those that are interested: https://github.com/cmu-db/noisepage/pull/1504/commits/066005bc9a770f7247fef38f30e02170e3a9a8b9
