### ISSUE TITLE
Check whether parser can populate AggregateExpression::value_idx

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#450]
In porting over the Peloton optimizer, @17zhangw had to add back the `value_idx` field to the `AggregateExpression` object:

https://github.com/cmu-db/peloton/blob/master/src/include/expression/aggregate_expression.h#L132

But we are not sure where this field should be populated. We think that it could be provided by the parser if the information is available:

https://github.com/cmu-db/terrier/blob/master/src/parser/postgresparser.cpp#L583-L595

Please coordinate with @17zhangw + @mush-zhang to understand this particular issue.

**Comment by lmwnshn** [comment]
`AggregateExpression::value_idx_` is private and on [searching](https://github.com/cmu-db/peloton/search?q=SetValueIdx&unscoped_q=SetValueIdx), `AggregateExpression::SetValueIdx` is only called by [expression_util.h::EvaluateExpression](https://github.com/cmu-db/peloton/blob/a045cfc95bf349742a8101aee65e22efd9ec8096/src/include/expression/expression_util.h#L581). (not to be confused with `TupleValueExpression` or `ParameterValueExpression`)

To my (shaky) understanding,
1. we have `ExprMap` which maps `AbstractExpression * -> unsigned` where the unsigned represents an operator column offset,
2. to compute this map, we had to [evaluate](https://github.com/cmu-db/peloton/blob/a045cfc95bf349742a8101aee65e22efd9ec8096/src/include/expression/expression_util.h#L559) all our children,
3. I'm not too sure how the map was populated [here](https://github.com/cmu-db/peloton/blob/a045cfc95bf349742a8101aee65e22efd9ec8096/src/include/expression/expression_util.h#L485) though..

It looked [hacky](https://github.com/cmu-db/peloton/blob/master/src/include/expression/aggregate_expression.h#L78) and it was not clear to me what it was doing.

I'm also not sure why you need it. 
1. As far as I can tell, [GetValueIdx](https://github.com/cmu-db/peloton/search?q=GetValueIdx&unscoped_q=GetValueIdx) is not called for `AggregateExpression` in the optimizer. Only for `ParameterValueExpression`.
2. So does that mean you need it for the hackyish `Evaluate`? That's the only place it seems to be used.

@17zhangw @mush-zhang

**Comment by 17zhangw** [comment]
I don't think `terrier` has any of the `Evaluate` functions for expressions.

I am under the impression we need `value_idx_` for `AggregateExpression` under the same line of reasoning for `TupleValueExpression/DerivedValueExpression`.

**Comment by lmwnshn** [comment]
No, and I think that was a design decision (to avoid evaluating expressions too much, although I do see some need for it in the optimizer).

I am not sure I follow that line of reasoning, sorry, could you elaborate? Do we need a value_idx_ with the same semantics as Peloton's?

In the [commit](https://github.com/cmu-db/peloton/commit/ed79063ea41f7700c0419abc0cd6135ed320b8c4) that introduced value_idx to AggregateExpression, it seemed they were introduced to "Add support for exprs with multiple aggregate". The "for now only support one child" seems to be a stale comment, I'm not sure if it still applies. I'm not very sure how to read their sum(a) + max(b) example, but it seems like they stuck a projection on top of the aggregate expression's result.

How are you ultimately using value_idx? I'm trying to figure out the meaning you want. If we're saying the parser can populate this, value_idx should be "statically" known (since we are not evaluating anything down here), so what should value_idx be for:

foo (a int, b int, c int)

1. select sum(a) from foo;
2. select sum(a)+max(b) from foo;
3. select sum(a+b) from foo;
4. select sum(x) from (select sum(a+b) x from foo) f;

Thanks!

**Comment by 17zhangw** [comment]
The reasoning, as I understand it, behind `value_idx_` for TupleValueExpression (similarly for AggregateExpression) is that for a given tuple (vector of values), the `value_idx_` is the corresponding offset into that tuple. 

The optimizer does not use the `value_idx`, it merely sets the AggregateExpression's `value_idx` for parts later in the system to use (i.e the planner/codegen in Peloton). I think this boils down to whether the `value_idx` is still needed later on?

**Comment by lmwnshn** [comment]
`value_idx` has been ejected.
