### ISSUE TITLE
clang-tidy: bugprone-exception-escape

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/noisepage#503]
We currently have this check disabled. However it should be re-enabled and the associated fixes should be applied to the codebase. I believe it mostly complains about destructors that might throw which shouldn't happen. It may just be a matter of sprinkling noexcept where appropriate.

**Comment by tli2** [comment]
This may have limited effect, as I don't believe `noexcept`s are actually enforced in C++. An example would be  if you call a function that is not `noexcept` in a destructor, it is still allowed to compile, despite the possibility of an exception being thrown.

This probably has to do with backward compatibility and such (e.g. free() is not marked with  `noexcept` because it is from C).  I think in practice it tends to mean "You should not try-catch a noexcept and let the program crash if it does throw.". This is implicit for destructors as you cannot try-catch them.

See http://modernescpp.com/index.php/c-core-guidelines-the-noexcept-specifier-and-operator.

**Comment by vbaderks** [comment]
Some feedback on the comments of @tli2:

- noexcept will be checked at runtime by any conforming C++17 compiler. If an exceptions is thrown from a function that is explicit or implicit marked as noexcept and not caught, the C++runtime will call std::terminate(), which by default will abort the application. This may not be the desired behavior.

- All functions from C (marked with extern "C") are considered implicit noexcept by the compiler.

- A destructor will be made implicit noexcept or noexcept(false) depending on the members of the class. If you like you can mark a destructor explicitly noexcept(false), which indicated to the compiler that this destructor can throw. Best practice is of course to design non throwing destructors.

**Comment by lmwnshn** [comment]
WONTFIX.
