### ISSUE TITLE
Add Support for Analyze Operators

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#716]
We need to add support for taking the `ANALYZE` SQL query all the way through our binder + optimizer.

1. Add a new class `LogicalAnalyze` to [logical_operators.h](https://github.com/cmu-db/terrier/blob/master/src/include/optimizer/logical_operators.h). It should contain the same data members as [AnalyzeStatement](https://github.com/cmu-db/terrier/blob/master/src/include/parser/analyze_statement.h) and [AnalyzePlanNode](https://github.com/cmu-db/terrier/blob/master/src/include/planner/plannodes/analyze_plan_node.h).

2. Add a new class `Analyze` to [physical_operators.h](https://github.com/cmu-db/terrier/blob/master/src/include/optimizer/physical_operators.h). Again, it should have the same members as `LogicalAnalyze`.

3. Modify `BindNodeVisitor::Visit` to make sure that it checks all the data members from `AnalyzeStatement` -- Right now it looks like it only checks table names.

4. Modify `QueryToOperatorTransformer::Visit` to support converting `AnalyzeStatement` into `LogicalAnalyze`. The method is currently unimplemented: https://github.com/cmu-db/terrier/blob/master/src/optimizer/query_to_operator_transformer.cpp#L587-L590

5. Modify the query optimizer to transform `LogicalAnalyze` into `Analyze`. I don't know how we do this for CREATE operators, so you will need to check with @esargent28 / @17zhangw.

6. Modify `PlanGenerator` to add a new `Visit` method that transforms `Analyze` into `AnalyzePlanNode`.

**Comment by malin1993ml** [comment]
Maybe we can directly transform the `LogicalAnalyze` to `Scan`+`Aggregate`, or `Scan`+`Aggregate`+`Analyze` (for saving the results)? That way we can probably reuse lots of the cogen logic for aggregation.

**Comment by gengkev** [comment]
I think all of the items in this issue are basically complete thanks to #743, right? (Except for possibly 3: `BindNodeVisitor::Visit` doesn't look like it is checking the columns for validity, which maybe it should be...?)

**Comment by rohanaggarwal7997** [comment]
Yup something like this should be present. I remember having some discussion with matt after which we decided not to change that right now. But I do not remember why. But I think adding a small code like this wont make any harm.
      for (const auto &col : *analyze_columns) {
        if (!BinderContext::ColumnInSchema(table_schema, col)) {
          throw BINDER_EXCEPTION("Insert column does not exist");
        }
      }

**Comment by jkosh44** [comment]
Is this a good place to track my progress on Analyze or should I open a new issue?

Here is how I view the tasks needed to implement Analyze and my progress so far:
https://github.com/jkosh44/noisepage/tree/analyze

- [X] Get Analyze through optimizer
  - [X] Make sure that we can generate a cost for Analyze and fix any issues that may occur 
  - [X] Generate aggregate query plan to get statistics on columns
- [ ]  Implement Top K and Histogram Aggregators
  - [ ] Add serialization and de-serialization methods for Top K and Histogram data structures
    - The approach I plan on using is to convert to json via `nlohmann` and then dump the results as a byte array
    - One thing I'm not sure how to do is serialize and deserialize `madoka::Sketch` since it's an external library and has no serialization methods. You can save it to a file, and even save it to an anonymous file (i.e. only heap memory), but it doesn't seem possible to locate the memory address where it's stored.
  - [ ] Add bytecodes, bytecode generation, bytecode handling, semantic checking, and vm interpertation.
    -  [ ] Pass the execution context down for Top K and Histogram so it can allocate space for the string results.
- [ ] Add codegen for Analyze

**Comment by jkosh44** [comment]
The aggregators are almost finished, all that's left is to implement serialization for them. In the meantime I did some testing that seems to indicate the aggregators are otherwise working. I made Top K always serialize into the string "TOPK" and Histograms always serialize into the string "HISTOGRAM". Then I temporarily changed the parser so that `MAX` parsed into the TopK aggregate and `MIN` parsed into the Histogram aggregate. These were the results.

```
noisepage=# CREATE TABLE foo(a int);
CREATE TABLE
noisepage=# INSERT INTO foo VALUES(1);
INSERT 0 1
noisepage=# SELECT MAX(a), MIN(a), AVG(a) FROM foo;
 ?column? | ?column?  | ?column? 
----------+-----------+----------
 TOPK     | HISTOGRAM | 1.000000
(1 row)
```

**Comment by jkosh44** [comment]
After implementing almost all of serialization (everything but the underlying `madoka::Sketch`), if we repeat the above test we get the following
```
noisepage=# CREATE TABLE foo(a int);
CREATE TABLE
noisepage=# INSERT INTO foo VALUES(1);
INSERT 0 1
noisepage=# INSERT INTO foo VALUES(50);
INSERT 0 1
noisepage=# SELECT MAX(a), MIN(a), AVG(a) FROM foo;

                                                                       ?column?                                                                       |                                                         ?column?                                                         | ?column?  
------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-----------
 {"bins":[{"count":1.0,"point":5e-324},{"count":1.0,"point":2.47e-322}],"max_bins":64,"maximum":2.2250738585072014e-308,"minimum":5e-324,"total":2.0} | {"entries":[[5e-324,1],[2.47e-322,1]],"min_count":1,"min_key":2.47e-322,"numk":16,"sketch":{"total_count":4,"width":64}} | 25.500000
(1 row)


```

**Comment by jkosh44** [comment]
Serializing and Deserializing the underlying `Madoka::Sketch` is causing me some issues. The documentation can be found here: https://www.s-yata.jp/madoka/doc/cpp-api.html

Here are some approaches I've thought about so far:
- Convert the entire object directly into binary. The issue with this is that looking at the class it contains good amount of pointers as fields. So if we convert the object to binary, we end up capturing the memory addresses of these pointers and not the underlying data. That means when we de-serialize we have no way of knowing if that's still the correct address and will likely get a Segfault.
- The API provides methods to save/load to/from memory mapped files. One option would be to save to a file and serialize the contents of this file, though this isn't really a great option to rely on file I/O for serialization. However if you pass in a null file path then it will use an anonymous file which is essentially just a block of memory on the heap with no underlying file. This would work really well, but there doesn't to be a way of getting this address after saving or supplying an address for loading. 
- We could just not serialize or de-serialize the sketch object. It is only used for statistics on elements outside of the top k so it's not the most important information compared to the top k. This would mean that the sketch information is lost on serialization. This is not really a great option because it basically makes the sketch useless. We don't ever use TopK without first serializing it, so we would never actually take advantage of the underlying sketch object.
- We could find a new implementation or make our own implementation with serialization built in.
