### ISSUE TITLE
Select Star with Table Qualifier Does Not Work

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#780]
A query with `SELECT *` works on one or multiple tables:

```
terrier=# CREATE TABLE xxx (id INT);             
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1),(2),(3),(4);
INSERT 0 4
terrier=# CREATE TABLE yyy (id INT);
CREATE TABLE
terrier=# INSERT INTO yyy VALUES (1),(2),(3),(4);
INSERT 0 4
terrier=# SELECT * FROM xxx JOIN yyy ON xxx.id = yyy.id;
 id | id 
----+----
  1 |  1
  2 |  2
  3 |  3
  4 |  4
(4 rows)
```

But if I add the table name as a qualifier in the output list, it does not work. This query should return the columns from table `xxx` and nothing from table `yyy`:
```
terrier=# SELECT xxx.* FROM xxx JOIN yyy ON xxx.id = yyy.id;
ERROR:  binding failed
```

**Comment by tpan496** [comment]
@apavlo The problem is in the parser. In postgresparser.cpp, `ColumnRefTransform` generates either a `StarExpression` or a `ColumnValueExpression`. Since we need something like 'xxx.*', it does not apply to either use case:
- 'StarExpression' does not refer to any tables
- 'ColumnValueExpression' takes only strings for 'column_name'. 
I am not sure how to fix this. Should we do this in the parser or somewhere else? I am not aware of any expressions that can describe the table qualifier. I have tried setting 'column_name' to '*', but obviously it doesn't work because the binder is not configured for this as well.

**Comment by lmwnshn** [comment]
Still an issue as of 2020-10-19.
